### PR TITLE
Show custom error messages

### PR DESCRIPTION
**Pull request by santiagodoldan**

### CODE REVIEW

**Comment by santiagodoldan** [comment]
This should fix this issue https://github.com/microsoftly/BotTester/issues/51

**Comment by microsoftly** [comment]
Looks good to me.

Please add a test to BotTester.spec.ts with the title "Can show custom error messages" and add the test to the README.md documentation and I'll be ready to merge and release an updated package.

sidenote: I've changed the base to from master to dev. Once dev is ready for publishing, the docs are recompiled, version number bumped, package is published, then dev is merged into master.

**Comment by santiagodoldan** [comment]
@microsoftly should I add a test for each matcher? https://github.com/microsoftly/BotTester/blob/master/src/assertionLibraries/ChaiExpectation.ts#L39-L53 looks like the deep include doesn't use the given message

**Comment by microsoftly** [comment]
@santiagodoldan yes, please explicitly test each method. 

I think having deep include also have the message could be useful. It shouldn't be too much work to extend it as well.

Only one of the new tests needs to be added to the documentation. The rest can be put in the [cases not for docs](https://github.com/microsoftly/BotTester/blob/master/test/BotTester.spec.ts#L421)

**Comment by santiagodoldan** [comment]
@microsoftly 

First of all, there's already a test file https://github.com/microsoftly/BotTester/blob/master/test/BotTesterFailure.spec.ts that test the error messages, the issue I see there is that `chai` includes both messages in the Error object (the format is "new-message:old-message") and this expectation https://github.com/microsoftly/BotTester/blob/master/test/BotTesterFailure.spec.ts is not comparing if the string is equal, it checks if the error message contains that string, which is true because is the default message that chai uses.

Regarding the test file, I was able to test the `toInclude` just passing the new custom message, I also was able to test the `notToBeEmpty` passing an empty array to the `sendMessageToBot` and also the `toBeTrue` passing a regexp.

The only one I can't test is the `toEqual`, I think the line that uses that expectation can't be reached, here you have the code https://github.com/microsoftly/BotTester/blob/master/src/ExpectedMessage.ts#L71-L72 and https://github.com/microsoftly/BotTester/blob/master/src/ExpectedMessage.ts#L71-L72, that default block isn't executed IMO.

**Comment by santiagodoldan** [comment]
@microsoftly another thing, would you like to move this expectation https://github.com/microsoftly/BotTester/blob/master/src/ExpectedMessage.ts#L50 out of the constructor? because that fails without executing `runTest()`

**Comment by santiagodoldan** [comment]
@microsoftly regarding what `chai` does with the message https://github.com/chaijs/chai/blob/master/lib/chai/utils/getMessage.js#L49, do you want to remove the old message or is that ok? let me know what would you like to do, so I can finish the PR, thanks :)

**Comment by microsoftly** [comment]
Removing the expect out of the constructor is fine.

I'm not sure which old message you're referring to, but I'll let you pick your best judgement. I'm fine W/ the PR as is.

**Comment by microsoftly** [comment]
as for https://github.com/microsoftly/BotTester/blob/master/src/ExpectedMessage.ts#L71-L72, it's been a while, but I'm pretty sure that's for ignoring internal save messages that are used to get the session loader to work properly

**Comment by santiagodoldan** [comment]
@microsoftly 

About the message, here you have an example of how it looks

`Bot should have responded with 'NOPE', but was 'how are you doing?: expected [ 'NOPE' ] to include 'how are you doing?'`

If that's ok, let's merge the PR then :)

**Comment by microsoftly** [comment]
great

**Pull request merged**
